language: generic
sudo: required

notifications:
  email: false

env:
  global:
    - GS_HOME=$TRAVIS_BUILD_DIR/GsDevKit_home
    - GS_SCRIPTS=$GS_HOME/bin
    - GSSQUEAK_SCRIPTS=$GS_HOME/shared/repos/BP2017RH1/tools/scripts
    - PATH=$PATH:$GS_HOME/bin
  matrix:
    - TEST=BasicGs

git:
  lfs_skip_smudge: true
  depth: 5

branches:
  only:
    - master

install:
  - tools/scripts/setupGs.sh
  - tools/scripts/createStones.sh

script:
  - tests/testTravisCI.sh

