sudo: required

env:
  GS_HOME=$TRAVIS_BUILD_DIR/GsDevKit_home
  GS_SCRIPTS=$GS_HOME/bin
  GSSQUEAK_SCRIPTS=$GS_HOME/shared/repos/BP2017RH1/tools/scripts
  PATH+=$GS_HOME/bin

git:
  lfs_skip_smudge: true
  depth: 5

branches:
  only:
    - master

install:
  - tools/scripts/setupGs.sh
  - tools/scripts/setupTode.sh
  - tools/scripts/createStones.sh

script: skip
