sudo: required

env:
  GS_HOME=$TRAVIS_BUILD_DIR/GsDevKit_home

git:
  lfs_skip_smudge: true
  depth: 5

branches:
  only:
    - master

install:
  - tools/scripts/setupGs.sh
  - tools/scripts/setupTode.sh
script: true
